Vagrantfile
redhat-beyond/FitMeet pull request #1
Opened 2023-03-16 16:46 UTC by Ofekmn

2023-03-17 13:44 UTC, talko611 commented
Hi Ofek, @Ofekmn 
I think you can add the HTTP connection to the VM. other than that looks fine to me.

2023-03-17 14:35 UTC, Ofekmn commented
> Hi Ofek, @Ofekmn I think you can add the HTTP connection to the VM. other than that looks fine to me.

Done.

2023-03-19 12:43 UTC, talko611 commented
Looks great from my perspective!

2023-03-19 14:34 UTC, talko611 commented
One last thing. In my opinion, it would be cleaner to squash all commits into 1

2023-03-19 15:19 UTC, kobihk commented
> One last thing. In my opinion, it would be cleaner to squash all commits into 1

@talko611 you don't have to do it in this phase because we can do it once we merge the PR we have the option to do "squash and merge"

2023-03-19 15:51 UTC, SaarOrus approved these changes
LGTM

2023-03-19 16:12 UTC, kobihk requested changes
@Ofekmn Please create an issue about this PR
then add a description to this PR as you can see in: 
https://github.com/redhat-beyond/team2/pull/2
but please use the supported keywords as you can see in:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
in this way, you make sure that when PR will merge, the relevant issue will close automatically.

2023-03-19 17:17 UTC, Ofekmn commented on .gitignore
> +.vagrant
Done.

2023-03-19 19:38 UTC, rotem2022 approved these changes

2023-03-20 08:56 UTC, kobihk approved these changes

2023-03-20 08:58 UTC, merged