Adding Event feed
redhat-beyond/FitMeet pull request #105
Opened 2023-05-16 21:44 UTC by Sendy459

### What this PR does?

contains links for event creation and event info
feature to filter the events by category and location.
with styling .

### Notes for reviewer

### Related Issue

Resolves #102 

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes
- [ ] The changes in this PR do not require tests
- [x] The changes in this PR require tests that are not added yet

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

2023-05-17 06:55 UTC, SaarOrus approved these changes
Looks great!

2023-05-17 07:10 UTC, rotem2022 commented on static_home_page/templates/home_page/all_events.html
pleas add a screenshot of the change

2023-05-17 07:11 UTC, rotem2022 commented on static_home_page/templates/home_page/all_events.html
> +</html>
also here I think you should add a new line

2023-05-17 07:12 UTC, Ofekmn requested changes

2023-05-17 07:12 UTC, Ofekmn commented on static_home_page/static/web_page_css.css
> +}
Please a newline at the end of file.

2023-05-17 07:12 UTC, Ofekmn commented on static_home_page/templates/home_page/all_events.html
> +</html>
Likewise. ^

2023-05-17 07:27 UTC, talko611 commented on static_home_page/templates/home_page/all_events.html
> +<html lang="en">
This lines are not needed here you inherit this from the base.html

2023-05-17 07:29 UTC, talko611 commented on static_home_page/templates/home_page/all_events.html
> +</head>
You are entering an `<head>`  inside an `<body>` (This whole file is inside a body tag of the base.html file) are you sure this is the correct way to render the page?

2023-05-17 09:47 UTC, talko611 commented on static_home_page/views.py
> +                events = events.filter(location__name=location)
You can use the event manager search method to apply multiple filters in one call

2023-05-17 11:33 UTC, rotem2022 submitted a review, later dismissed

2023-05-17 12:18 UTC, talko611 requested changes

2023-05-17 12:18 UTC, talko611 commented on fit_meet/urls.py
> +    path('<int:user_id>/event/info/', event_views.view_event, name='view_event'),
You are creating here another path to the event views, which is wrong 
The event URLs that work with the event views functions 
should be in this pattern: `localhost:<port number>/<user id>/event/<name of the resource and query params if needed>` (<> are place holders and the text inside describes which value should be there)
This line `path('<int:user_id>/event/', include("event.urls"))` already tell django to look for matching URLs also event/urls.py
Instead, you should change the href attribute of the `<a>` to match the existing path defined in the event/url.py

2023-05-17 14:46 UTC, Sendy459 commented on fit_meet/urls.py
> +    path('<int:user_id>/event/info/', event_views.view_event, name='view_event'),
Thank you for your review ,
However, I'm having some trouble fully understanding the changes you're proposing. Could you please provide a specific example demonstrating how you'd like the urls path to be structured?
please clarify the changes needed in the href attribute and how it should match with the defined paths.

2023-05-18 09:34 UTC, rotem2022 approved these changes

2023-05-18 09:35 UTC, talko611 submitted a review, later dismissed

2023-05-18 09:40 UTC, Ofekmn submitted a review, later dismissed

2023-05-18 10:45 UTC, kobihk requested changes

2023-05-18 10:45 UTC, kobihk commented on event/views.py
> +        user_id = None
you can do it in one line like:
```suggestion
    user_id = request.user.id if request.user.is_authenticated else None
```

2023-05-18 10:45 UTC, kobihk commented on static_home_page/static/web_page_css.css
> +  background-color: #d1a843;
I think you missed the curly braces closure
```suggestion
  background-color: #d1a843;
  }
```

2023-05-18 10:45 UTC, kobihk commented on static_home_page/views.py
> +def event_list(request):
I can see that you already have it in:
event/views.py
Do we still need this code?

2023-05-18 10:45 UTC, kobihk commented on event/templates/event/all_events.html
> +</html>
you have it already in the base.html file
```suggestion

```

2023-05-18 10:45 UTC, kobihk commented on event/templates/event/all_events.html
> +</head>
maybe all the "head" lines should be part of the base.html file

2023-05-18 11:54 UTC, Ofekmn approved these changes

2023-05-18 11:55 UTC, rotem2022 approved these changes

2023-05-18 12:37 UTC, kobihk approved these changes

2023-05-18 12:38 UTC, merged