Web Page files
redhat-beyond/FitMeet pull request #11
Opened 2023-03-21 16:27 UTC by Sendy459

I updated the empty html file @talko611 created
Added the css file,
Added images I used to create the Web Page.

2023-03-22 10:43 UTC, talko611 approved these changes

2023-03-22 12:25 UTC, rotem2022 approved these changes

2023-03-22 12:55 UTC, ygalblum commented on Vagrantfile
> +  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
Try not to commit commented lines

2023-03-22 12:55 UTC, ygalblum commented on Vagrantfile
> +  #   # Customize the amount of memory on the VM:
No need for extra `#`

2023-03-22 13:45 UTC, kobihk requested changes

2023-03-22 13:45 UTC, kobihk commented on static_home_page/static/WebPageCss.Css
> +}
Please add a new line at the end of the file

2023-03-22 13:45 UTC, kobihk commented on static_home_page/static/WebPageCss.Css
maybe it will be better to create file name suffix all lower case like:
static_home_page/static/WebPageCss.css

2023-03-22 13:45 UTC, kobihk commented on static_home_page/templates/home_page/index.html
> +			    FitMeet makes it easy to pick the best time and know who's coming,
```suggestion
			    FitMeet makes it easy to pick the best time and knows who's coming,
```

2023-03-22 13:45 UTC, kobihk commented on static_home_page/templates/home_page/index.html
> +					I like playing tennis and travelling.</p>
```suggestion
					I like playing tennis and traveling.</p>
```

2023-03-22 13:45 UTC, kobihk commented on static_home_page/templates/home_page/index.html
>  </html>
Please add a new line at the end of the file

2023-03-22 13:45 UTC, kobihk commented on Pipfile
> +flake8 = "*"
I think you are not using it in this PR

2023-03-22 14:30 UTC, kobihk commented on static_home_page/static/WebPageCss.Css
@Sendy459 IMHO this is the reason to prefer file names all lowercase with underscore separators like:
web_page_css.css

2023-03-22 17:31 UTC, kobihk requested changes

2023-03-23 11:55 UTC, kobihk requested changes

2023-03-23 11:55 UTC, kobihk commented on static_home_page/templates/home_page/index.html
> +			    FitMeet makes it easy to pick the best time and know who's coming,
please refix it

2023-03-23 11:55 UTC, kobihk commented on static_home_page/templates/home_page/index.html
> +					I’m a professional sailor and also diving instructor . love snowboarding .</p>
please refix it

2023-03-23 11:55 UTC, kobihk commented on static_home_page/templates/home_page/index.html
> +					I like playing tennis and travelling.</p>
please refix it

2023-03-23 11:55 UTC, kobihk commented on static_home_page/templates/home_page/index.html
>  </html>
please refix it

2023-03-23 12:11 UTC, kobihk approved these changes

2023-03-23 12:18 UTC, Ofekmn approved these changes

2023-03-23 12:26 UTC, Ofekmn approved these changes

2023-03-23 13:33 UTC, merged