Adding team view
redhat-beyond/FitMeet pull request #112
Opened 2023-05-17 15:43 UTC by rotem2022

### What this PR does?

In this PR I added generate team button
added files:

1. event/migrations/0007_static_data.py :

- Create users and events to facilitate testing the "Generate Team" button.
- This migration ensures that the necessary data is available for testing.

edit files:

1. event/templates/event/event_info.html : 

- Added a button to the file that allows generating teams for the event.
- Note that the generation can only occur once, as agreed upon.
- After clicking the button, a table displaying the generated teams will be shown.

2. event/urls.py :
- Include a relevant path for the newly added functionality.

3. event/views.py
- Make necessary changes to handle the team generation button functionality.
4. teams/models.py
- Implement any modifications required for the team generation feature.
5. teams/tests.py:
- Updated the test to ensure the correctness of the team generation functionality.

### Related Issue 

Resolves #94 

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

![teams3](https://github.com/redhat-beyond/FitMeet/assets/93313405/5fea6e7e-896d-4082-92b5-361f09c54cd5)
<img width="301" alt="teams button" src="https://github.com/redhat-beyond/FitMeet/assets/93313405/81ff6c0f-4188-48a6-bd1a-ab23526c40e8">

2023-05-17 19:22 UTC, Sendy459 approved these changes

2023-05-17 19:22 UTC, Sendy459 submitted a review, later dismissed

2023-05-18 09:14 UTC, Ofekmn approved these changes

2023-05-18 13:41 UTC, Sendy459 submitted a review, later dismissed

2023-05-18 13:49 UTC, Sendy459 submitted a review, later dismissed

2023-05-18 13:54 UTC, Ofekmn submitted a review, later dismissed

2023-05-18 14:00 UTC, rimonsh submitted a review, later dismissed

2023-05-18 14:09 UTC, ygalblum requested changes

2023-05-18 14:09 UTC, ygalblum commented on event/templates/event/event_info.html
> +    <button type="submit">Generate Teams</button>
I'm not an HTML guy, but, is the indentation supposed to look like that? For example, `form` starts in 8 spaces but ends in 0

2023-05-18 14:09 UTC, ygalblum commented on event/views.py
> +                     for user in UserEvent.objects.filter(teamID=teams[1].id)]
Combining the two conditions together allows you to go back one indentation
```suggestion
    if len(users_events) > 0 and users_events[0].teamID:
        teams = list(set([user_event.teamID for user_event in users_events]))
        team1 = [user.userID.user.username for user in UserEvent.objects.filter(teamID=teams[0].id)]
        team2 = [user.userID.user.username for user in UserEvent.objects.filter(teamID=teams[1].id)]
```

2023-05-18 14:09 UTC, ygalblum commented on event/views.py
> +            teams = list(set([user_event.teamID
You check `users_events[0].teamID`, and then run on the entire list. Is it guarantied that the rest of the items have it?

2023-05-18 14:09 UTC, ygalblum commented on event/views.py
> +            team1 = [user.userID.user.username
How are you sure that `len(teams) == 2`?

2023-05-18 14:09 UTC, ygalblum commented on teams/models.py
> +        team1 = Teams(name=f"{event_id}Team1")
Consider a seperator between the event_id and Team. 
```suggestion
        team1 = Teams(name=f"{event_id}-Team1")
```

2023-05-18 16:09 UTC, rotem2022 commented on event/templates/event/event_info.html
> +    <button type="submit">Generate Teams</button>
I'm not sure I understand your meaning, can you please explain?

2023-05-18 16:18 UTC, rotem2022 commented on event/views.py
> +                     for user in UserEvent.objects.filter(teamID=teams[1].id)]
This implementation is structured in this particular way due to the scenario where the length of the `user_event` is 0. In such cases, attempting to access `user_event[0].teamID` would result in an error.

2023-05-18 16:27 UTC, rotem2022 commented on event/views.py
> +            teams = list(set([user_event.teamID
Yes it is guarantied. If a user belonged to a team, it means that the teams are generated.
Therefore, it is guarantied there are 2 teams to the event.

2023-05-18 16:27 UTC, rotem2022 commented on event/views.py
> +            team1 = [user.userID.user.username
same as the above

2023-05-18 16:46 UTC, Sendy459 submitted a review, later dismissed

2023-05-18 16:53 UTC, ygalblum commented on event/templates/event/event_info.html
> +    <button type="submit">Generate Teams</button>
Indentation help read the document. So, I would expect that opening and closing a tag will happen in the same indentation. For example:
This is good:
```
<form>
</form>
```
This is not so much:
```
    <form>
        </form>
```

I think the issue actually starts a line before (the location of the if statement). So, it should be:
```
{% if team1|length == 0 %}
<form id="event-form" method="post">

    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Generate Teams</button>

</form>
{% else %}
...
```

2023-05-18 16:56 UTC, ygalblum commented on event/views.py
> +            teams = list(set([user_event.teamID
OK

2023-05-18 16:57 UTC, ygalblum commented on event/views.py
> +            team1 = [user.userID.user.username
OK

2023-05-18 22:17 UTC, rotem2022 commented on event/templates/event/event_info.html
> +    <button type="submit">Generate Teams</button>
Ok, thank you!

2023-05-19 06:17 UTC, SaarOrus approved these changes

2023-05-19 18:48 UTC, ygalblum approved these changes

2023-05-19 18:48 UTC, merged