Test Profile Update
redhat-beyond/FitMeet pull request #136
Opened 2023-06-01 12:33 UTC by SaarOrus

This PR adds a new test case to the edit profile functionality. The test, test_profile_update_view, ensures that the profile update view functions correctly.

Resolves #135

2023-06-01 13:34 UTC, Ofekmn submitted a review, later dismissed

2023-06-01 14:51 UTC, Sendy459 submitted a review, later dismissed

2023-06-01 15:12 UTC, kobihk requested changes

2023-06-01 15:12 UTC, kobihk commented on users/tests.py
> +
pytest-django provides some pytest fixtures to provide dependencies for tests so you don't really need these lines
https://pytest-django.readthedocs.io/en/latest/helpers.html#client-django-test-client
```suggestion
```

2023-06-01 17:20 UTC, kobihk approved these changes

2023-06-01 17:38 UTC, Ofekmn approved these changes

2023-06-02 08:03 UTC, Sendy459 approved these changes

2023-06-04 12:21 UTC, merged