Add architecture DFD files
redhat-beyond/FitMeet pull request #22
Opened 2023-03-29 19:00 UTC by Ofekmn

resolves #21

2023-03-30 10:31 UTC, rimonsh approved these changes

2023-03-30 11:29 UTC, Sendy459 submitted a review, later dismissed
Looks good to me

2023-03-30 11:30 UTC, rotem2022 approved these changes

2023-04-15 17:06 UTC, rotem2022 approved these changes

2023-04-16 11:46 UTC, ormergi requested changes
Hi, Ofek, please make sure to squash intermediate commits at least when the discussion is done and you got approve from a maintainer.

I think the diagram lack context in the sense of who performs the operation (the person that created the poll or the is it participants) and where it starts (chronologically).

Could you please add an entity that reflects the end user in each flow?
Also, please make sure the flow is described in a chronological way (e.g: right to left) where possible.

2023-04-20 07:49 UTC, rotem2022 submitted a review, later dismissed

2023-04-20 10:55 UTC, Ofekmn commented
> Hi, Ofek, please make sure to squash intermediate commits at least when the discussion is done and you got approve from a maintainer.
> 
> I think the diagram lack context in the sense of who performs the operation (the person that created the poll or the is it participants) and where it starts (chronologically).
> 
> Could you please add an entity that reflects the end user in each flow? Also, please make sure the flow is described in a chronological way (e.g: right to left) where possible.

The chronological order is from up to down when possible.

2023-04-20 14:03 UTC, ormergi approved these changes

2023-04-20 14:06 UTC, Sendy459 submitted a review, later dismissed

2023-04-20 14:21 UTC, kobihk requested changes

2023-04-20 14:21 UTC, kobihk commented on uml/DFD_diagram.png
@Ofekmn I can see that most of the Entities on the left side are User
maybe we can create one Entity for all

2023-04-20 14:57 UTC, Sendy459 submitted a review, later dismissed

2023-04-20 15:18 UTC, kobihk requested changes

2023-04-20 15:27 UTC, kobihk approved these changes

2023-04-20 15:28 UTC, Sendy459 approved these changes

2023-04-20 15:34 UTC, rotem2022 approved these changes

2023-04-20 16:36 UTC, merged