Adding teams model
redhat-beyond/FitMeet pull request #26
Opened 2023-04-10 11:01 UTC by rotem2022

need to fix flake8
#25

2023-04-10 14:23 UTC, Ofekmn approved these changes

2023-04-11 08:15 UTC, talko611 commented on teams/admin.py
> +# Register your models here.
You need to register your model to the admin site

2023-04-13 18:50 UTC, talko611 commented on teams/admin.py
> +# Register your models here.
You need to register the app to the admin app

2023-04-14 14:01 UTC, ygalblum reviewed
Please see and fix the flake8 errors

2023-04-15 17:07 UTC, rotem2022 commented on teams/admin.py
> +admin.site.register(Teams)
yes that is right, thank you

2023-04-16 07:08 UTC, SaarOrus submitted a review, later dismissed

2023-04-16 07:18 UTC, kobihk commented
@rotem2022 please fix the typo in the PR description:
tests.py

2023-04-16 07:18 UTC, kobihk commented
@rotem2022 please rebase and resolve the conflicts

2023-04-16 08:38 UTC, kobihk commented
> * tsest.py

2023-04-16 08:40 UTC, kobihk commented
@rotem2022 please fix the typo in the PR description:
tsest.py

2023-04-16 13:45 UTC, ormergi requested changes
Please fix the commit message title and format, the describption should be in the middle and  the sign-off at the bottom.
Also please change the description to elaborate what this change does and why you need it.

2023-04-16 13:45 UTC, ormergi commented on teams/models.py
> +    def __str__(self) -> str:
Why do we need this method?

If it is not used anywhere, you can remove it for now and add it when needed.

2023-04-16 14:06 UTC, rotem2022 commented on teams/models.py
> +    def __str__(self) -> str:
Ok, I removed this function.

2023-04-16 14:08 UTC, rotem2022 commented
> Please fix the commit message title and format, the describption should be in the middle and the sign-off at the bottom. Also please change the description to elaborate what this change does and why you need it.

I changed the commit description and added some explanation.

2023-04-17 06:03 UTC, ormergi commented
> I changed the commit description and added some explanation.

I see that you added an explanation to the PR description but the commit message is empty.
Please add an explanation to the commit message as well.
Also, you can use the `-s` flag to add the standard sign-off instead of writing it manually: 
`git commit -s` / `git commit --amend -s.

2023-04-17 11:41 UTC, rotem2022 commented
> > I changed the commit description and added some explanation.
> 
> I see that you added an explanation to the PR description but the commit message is empty. Please add an explanation to the commit message as well. Also, you can use the `-s` flag to add the standard sign-off instead of writing it manually: `git commit -s` / `git commit --amend -s.

All done.

2023-04-17 12:21 UTC, Sendy459 approved these changes

2023-04-18 08:32 UTC, Sendy459 approved these changes

2023-04-18 08:50 UTC, ygalblum requested changes

2023-04-18 08:50 UTC, ygalblum commented on fit_meet/settings.py
> +    'teams.apps.TeamsConfig'
Commas are allowed also on the last element. So, it's safer to add a comma to avoid creating issues to other PRs
```suggestion
    'teams.apps.TeamsConfig',
```

2023-04-18 08:57 UTC, rotem2022 commented on fit_meet/settings.py
> +    'teams.apps.TeamsConfig'
Yes I understand. I made the change.

2023-04-18 09:33 UTC, ygalblum submitted a review, later dismissed

2023-04-18 10:31 UTC, ygalblum approved these changes

2023-04-18 10:32 UTC, Ofekmn approved these changes

2023-04-19 13:49 UTC, kobihk requested changes

2023-04-19 13:49 UTC, kobihk commented on teams/tests.py
> +def create_team():
in this fixture, you create a specific team object 
so I think it will be better to call it like:
```suggestion
def team1():
```

2023-04-19 13:49 UTC, kobihk commented on teams/tests.py
> +    return team
I would define the name as a constant like:
TEAM1 = 'Team 1' 
because if you will want to check it, it will be easier to use the constant
```suggestion
    return Teams.objects.create(name=TEAM1)
```

2023-04-19 13:49 UTC, kobihk commented on teams/tests.py
> +        assert create_team in Teams.objects.all()
here it will be more readable like:
```suggestion
    def test_create_team(self, team1):
        team1.save()
        assert team1 in Teams.objects.all()
```

2023-04-19 13:49 UTC, kobihk commented on teams/tests.py
> +        assert create_team not in Teams.objects.all()
same ^^

2023-04-19 13:49 UTC, kobihk commented on teams/tests.py
> +
I think you can make more tests like for validation of team name:
 - long name
 - empty name
 - a name with special characters
 - same name
for most of the tests, you can use pytest.mark.parametrize as you can see for example in:
https://github.com/EdDev/django-testing-tutorial/blob/main/member/tests.py#L146

2023-04-19 14:26 UTC, ormergi requested changes

2023-04-19 14:26 UTC, ormergi commented on teams/tests.py
> +        assert create_team not in Teams.objects.all()
Please note that these tests don't test the app business login, it tests Django built-in ORM functionality.
I would remove them because they don't test the app business logic.

2023-04-20 06:50 UTC, rotem2022 commented on teams/tests.py
> +
what do you mean by same name?

2023-04-20 08:37 UTC, rotem2022 commented on teams/tests.py
> +        assert create_team not in Teams.objects.all()
Ok, I removed them.

2023-04-20 08:55 UTC, Sendy459 approved these changes

2023-04-20 09:53 UTC, ormergi approved these changes

2023-04-20 10:12 UTC, kobihk commented
@rotem2022 AFAICS the title and description of this PR should be updated because you already created the event entity in #52

2023-04-20 10:19 UTC, kobihk requested changes

2023-04-20 10:19 UTC, kobihk commented on teams/tests.py
> +            Teams.objects.create(name=EMPTY_NAME).full_clean()
as you can see the code in both tests looks the same except for the input of the name 
for this reason, you have the option to use pytest.mark.parametrize 
as you can see for example in:
https://github.com/EdDev/django-testing-tutorial/blob/main/member/tests.py#L146

2023-04-20 10:19 UTC, kobihk commented on teams/tests.py
> +            Teams.objects.create(name=EMPTY_NAME).full_clean()
you can also add a method that checks the name with special characters

2023-04-20 10:19 UTC, kobihk commented on teams/tests.py
> +
Can I create a team name with the exact same name? 
like 2 teams with the same name "Team 1"

2023-04-20 10:59 UTC, rotem2022 commented
> @rotem2022 AFAICS the title and description of this PR should be updated because you already created the event entity in #52

All done.

2023-04-20 11:03 UTC, rotem2022 commented on teams/tests.py
> +            Teams.objects.create(name=EMPTY_NAME).full_clean()
done.

2023-04-20 11:08 UTC, SaarOrus submitted a review, later dismissed

2023-04-20 11:19 UTC, Sendy459 approved these changes
LGTM

2023-04-20 16:09 UTC, rotem2022 commented on teams/models.py
> +    def save(self, *args, **kwargs):
I added a test for the save.

2023-04-23 05:42 UTC, ormergi approved these changes

2023-04-23 05:50 UTC, kobihk approved these changes

2023-04-23 06:09 UTC, Sendy459 approved these changes

2023-04-23 06:11 UTC, Ofekmn approved these changes

2023-04-23 06:12 UTC, merged