Adding poll entity
redhat-beyond/FitMeet pull request #28
Opened 2023-04-10 14:06 UTC by Sendy459

first stage in resolving #27 and creating the final poll entity.

2023-04-10 14:21 UTC, Ofekmn submitted a review, later dismissed

2023-04-11 08:14 UTC, talko611 commented on fit_meet/settings.py
> +    BASE_DIR / "static_home_page/static",
Already change it in my PR. you don't need to change it as well

2023-04-11 08:14 UTC, talko611 commented on poll/admin.py
> +# Register your models here.
You should register your model to the admin app

2023-04-11 08:14 UTC, talko611 commented on poll/models.py
> +    end_time = models.DateTimeField(default=timezone.now)
I don't think giving now as the default end time to the poll when it's been created, is correct. Maybe 2 days from the creation time will be better.

2023-04-11 18:13 UTC, Ofekmn commented on poll/models.py
> +
Hey, I am not sure if you noticed, but the commit didn't pass the flake8 test as there needs to be another empty line here.

2023-04-12 08:15 UTC, talko611 approved these changes

2023-04-12 08:28 UTC, Ofekmn approved these changes

2023-04-12 08:28 UTC, SaarOrus submitted a review, later dismissed
LGTM

2023-04-13 08:40 UTC, kobihk commented
@Sendy459 please update the PR description according to:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
to be able to close issue #27 automatically when we merge this PR

2023-04-13 09:00 UTC, kobihk commented
@Sendy459 please rebase

2023-04-13 15:31 UTC, Ofekmn submitted a review, later dismissed

2023-04-13 18:46 UTC, talko611 submitted a review, later dismissed

2023-04-14 13:47 UTC, ygalblum commented on poll/models.py
> +    # event = models.OneToOneField(Event)  # waiting for tal to create and merge the event
I'm not a fan of committing commented code. I think it's better to remove this line and open a new issue. This way you will remember to add it

2023-04-14 13:56 UTC, ygalblum commented
LGTM, but you need to rebase

2023-04-16 10:53 UTC, ormergi requested changes
Hi Daniel, please squash the second and third commits to the first one.

Fixing review comments should be done on the commit that introduces the change and not in a new commit of its own.
Keeping the commits like this keeps git history clean and easier to follow changes in the code base.

2023-04-16 10:53 UTC, ormergi commented on poll/models.py
> +    # event = models.OneToOneField(Event)  # waiting for tal to create and merge the event
Please remove this comment, you can comment it on the PR that adds it.

2023-04-16 11:22 UTC, Ofekmn submitted a review, later dismissed

2023-04-16 11:37 UTC, ormergi commented on poll/models.py
> +    # event = models.OneToOneField(Event)  # waiting for tal to create and merge the event
@Sendy459 I see that only part of this is removed, I meant to remove the whole line.
What we have now is dead code (code that will never run), you can suggest adding this to the relevant PR.

2023-04-16 11:47 UTC, SaarOrus approved these changes

2023-04-16 12:22 UTC, rotem2022 submitted a review, later dismissed

2023-04-16 12:31 UTC, Sendy459 commented on poll/models.py
> +    # event = models.OneToOneField(Event)  # waiting for tal to create and merge the event
oh ok I thought you meant the second part .

2023-04-16 12:36 UTC, Sendy459 commented on poll/models.py
> +    # event = models.OneToOneField(Event)  # waiting for tal to create and merge the event
fixed

2023-04-16 13:37 UTC, ormergi approved these changes
lgtm

2023-04-16 13:41 UTC, ormergi requested changes
Please change the commit message to describe why this change is necessary and what it does, and add a sign-off.

2023-04-17 05:58 UTC, ormergi commented
@Sendy459  the commit message has /n instead of new line.
Regarding the sign-off, you can add the standard sign-off using the `-s` flag: `git commis -s ..` git commit --amend -s ...`

2023-04-17 07:09 UTC, ormergi approved these changes
Thanks for the changes.

2023-04-17 07:43 UTC, rotem2022 approved these changes

2023-04-17 08:09 UTC, talko611 approved these changes

2023-04-17 08:11 UTC, merged