Adding setup.sh file
redhat-beyond/FitMeet pull request #3
Opened 2023-03-17 17:55 UTC by SaarOrus

2023-03-18 16:22 UTC, talko611 commented
Looks great! 
After PRing my code today in order the make the automation work, could you please add on change to the file
After the line "pipenv sync --dev" (line 11) please add this line:
"cd src"
Other than that I think it would be cleaner if you edit your commits into one

2023-03-19 14:31 UTC, talko611 commented
All looks great to me!

2023-03-19 14:33 UTC, Ofekmn commented
Looks great!

2023-03-19 14:48 UTC, kobihk commented
@talko611 @Ofekmn I can see that you added a comment with "Looks great!" and "All looks great to me!"
but when you approve a PR we want you to add "Approve" in this way it is easier to see it.

Please add approve by:
1. Go to "File changed" tab 
2. Click on "Review changes"
3. Choose "Approve"
4. (optional) Add comment

2023-03-19 14:52 UTC, Ofekmn approved these changes
Looks great!

2023-03-19 15:05 UTC, talko611 approved these changes

2023-03-19 15:08 UTC, kobihk requested changes
@SaarOrus Please create an issue about this PR 
then add a description to this PR as you can see in: #2 
but please use the supported keywords as you can see in:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
in this way, you make sure that when PR will merge, the relevant issue will close automatically.

2023-03-19 15:08 UTC, kobihk commented on setup.sh
> +# password if we don�t have sufficient privileges to run it
Please fix the "?" char
```suggestion
# password if we don't have sufficient privileges to run it
```

2023-03-19 19:37 UTC, rotem2022 approved these changes

2023-03-20 09:01 UTC, kobihk requested changes

2023-03-20 09:01 UTC, kobihk commented on setup.sh
> + (setsid pipenv run python manage.py runserver 0.0.0.0:8000 > runserver.log 2>&1 &)
please add a new line in the end of the file

2023-03-20 12:17 UTC, kobihk requested changes

2023-03-20 12:17 UTC, kobihk commented on setup.sh
> +
Please remove the space from line # 17
To make sure we will not see the notification about missing a new line at the end of the file
```suggestion

```

2023-03-20 13:38 UTC, merged