Adding Users app
redhat-beyond/FitMeet pull request #35
Opened 2023-04-12 14:32 UTC by SaarOrus

Resolve : #34

2023-04-14 14:02 UTC, rotem2022 approved these changes

2023-04-16 10:43 UTC, Ofekmn submitted a review, later dismissed

2023-04-16 11:55 UTC, ygalblum requested changes

2023-04-16 11:55 UTC, ygalblum commented on users/models.py
> +    image_url = models.CharField(max_length=40)
40 might be to short in some cases. No need to fail on this. From a quick look, I found the Django has a URLField model: https://docs.djangoproject.com/en/4.2/ref/models/fields/#urlfield

2023-04-16 13:52 UTC, ormergi requested changes
Hi Saar, please squash intermediate commits and fix the commit message to have a proper description (elaborate what this change does and why you need it) and a sign-off.
Also fix the PR description to explain what this PR does and why you need it, referencing to an issue is nice but its no replacement for the description.

2023-04-16 13:52 UTC, ormergi commented on users/models.py
> +    def __str__(self):
Why do we need this method?

If it is not used anywhere, you can remove it for now and add it when needed.

2023-04-17 06:37 UTC, ygalblum commented on users/models.py
> +    def __str__(self):
I've seen it in other models as well, I think it's auto-generated, no? `__str__` is the string representation of an instance. So, you won't see any direct calls to it

2023-04-17 07:41 UTC, ormergi commented on users/models.py
> +    def __str__(self):
From what I remember it's not auto-generated, @SaarOrus is its method auto-generated?

2023-04-17 08:44 UTC, SaarOrus commented on users/models.py
> +    def __str__(self):
@ormergi No, the __str__ method is not auto-generated.

2023-04-17 12:46 UTC, ormergi approved these changes
Thanks for the changes

2023-04-17 12:48 UTC, ygalblum approved these changes

2023-04-17 12:48 UTC, merged