Adding Pull Req template
redhat-beyond/FitMeet pull request #38
Opened 2023-04-13 16:04 UTC by rotem2022

Added file:
- pull_request_template.md

resolve #37

2023-04-15 10:24 UTC, rotem2022 commented on .github/pull_request_template.md
> +  CHANGELOG update
you are right, I updated the file so now it's suits better.

2023-04-16 11:30 UTC, ormergi requested changes
Hi Rotem, this is very nice I hope it will improve PRs quality.
Please see in-line comments.

2023-04-16 11:30 UTC, ormergi commented on .github/pull_request_template.md
> +### Connected Issue/Story
I would call it "Related Issue"

2023-04-16 11:30 UTC, ormergi commented on .github/pull_request_template.md
> +### Desired Outcome
How about "Why you need this PR" or "What this PR does"?

2023-04-16 11:30 UTC, ormergi commented on .github/pull_request_template.md
> +### Implemented Changes
I am not sure what this section should describe, how the change is implemented should be realized from the code diff.

2023-04-16 11:30 UTC, ormergi commented on .github/pull_request_template.md
> +- _How should the reviewer approach this PR_
I think this deserves its owns section (something like "Notes to reviewer")

2023-04-16 11:30 UTC, ormergi commented on .github/pull_request_template.md
> +*Feel free to copy this information from the connected issue.*
I would pass omit this section, no need to copy and paste the issue information there is a section for referencing issues.

2023-04-16 11:30 UTC, ormergi commented on .github/pull_request_template.md
> +
I would omit this section as well, tests (unit or e2e) should be an integral part of a PR that changes the code.
Also, this section would not make sense for PRs that change other things, e.g: docs, GitHub Actions manifests.

2023-04-17 20:10 UTC, rotem2022 commented
> Hi Rotem, this is very nice I hope it will improve PRs quality. Please see in-line comments.

Hi Or, thank you for all the notes!

2023-04-18 10:33 UTC, ygalblum approved these changes
LGTM

2023-04-20 06:31 UTC, ormergi approved these changes
LGTM

2023-04-20 06:32 UTC, merged