poll_suggestion entity
redhat-beyond/FitMeet pull request #39
Opened 2023-04-14 06:50 UTC by rimonsh

poll_suggestion entity, need to add dependencies with poll entity @Sendy459  + make sure every user can create up to one poll suggestion.

2023-04-14 12:38 UTC, Ofekmn requested changes

2023-04-14 12:38 UTC, Ofekmn commented on poll_suggestion/models.py
> +        return self.date,self.hour
Please add a whitespace like this to pass the flake8 test:
```suggestion
        return self.date, self.hour
```

2023-04-14 12:38 UTC, Ofekmn commented on poll_suggestion/models.py
> +    hour = models.CharField(max_length=20)
I believe it would be better to have a single DateTimeField for the suggested time.

2023-04-14 12:38 UTC, Ofekmn commented on .idea/vcs.xml
Please remove all the '.idea' files, as they are irrelevant to the PR and are IDE specific.

2023-04-14 15:09 UTC, SaarOrus requested changes
Please create an issue about this PR

2023-04-16 06:58 UTC, kobihk requested changes

2023-04-16 06:58 UTC, kobihk commented on .idea/vcs.xml
you can add the following line:
.idea/
in ".gitignore" file

2023-04-16 11:53 UTC, ormergi requested changes
Hi Rimon, please fix the PR description to describe what this PR does and why is it necessary, same goes for the commit message.

2023-04-16 11:53 UTC, ormergi commented on .idea/.gitignore
> +/workspace.xml
These files seem to not be related to this project (e.g: IDE config file).
If so you can set your local git to ignore them, see https://stackoverflow.com/questions/1753070/how-do-i-configure-git-to-ignore-some-files-locally

2023-04-18 11:42 UTC, kobihk requested changes

2023-04-18 11:42 UTC, kobihk commented on .gitignore
> +.idea/
please add a new line in the end of the file

2023-04-18 11:42 UTC, kobihk commented on poll_suggestion/models.py
> +    user_name = models.CharField(max_length=20)
AFAICS in the ERD:
https://github.com/redhat-beyond/FitMeet/blob/main/uml/Database_ER_diagram.png
it should be Poll_id instead of user_name

2023-04-18 11:44 UTC, kobihk commented
@rimonsh Please fix the flake8 and DCO checks

2023-04-19 13:28 UTC, kobihk requested changes

2023-04-19 13:28 UTC, kobihk commented on poll_suggestion/models.py
> +    poll_id = models.CharField(max_length=20)
IMHO the poll should be linked to it like:
```suggestion
    poll_id = models.ForeignKey(Poll, on_delete=models.CASCADE)
```

2023-04-19 14:27 UTC, rimonsh commented on poll_suggestion/models.py
> +    poll_id = models.CharField(max_length=20)
done.

2023-04-20 10:41 UTC, kobihk submitted a review, later dismissed

2023-04-20 13:45 UTC, ormergi requested changes
Hi Rimon,
Please squash intermediate commits.

Also, fix the first commit message in a way it describes why this change is necessary and what it does.
Note that 'Fixing XYZ' kind of description is vague and won't enable the reader to understand what is the commit about.
Changes that can be understood from the diff should not be mentioned (usually), such as removing imports, 
Also, the sign-off should be placed at the bottom of the commit message.

2023-04-20 13:45 UTC, ormergi commented on poll_suggestion/models.py
> +class poll_suggestion(models.Model):
The class name does not comply with python naming convention https://peps.python.org/pep-0008/#class-names

2023-04-20 13:45 UTC, ormergi commented on .gitignore
> +.idea/
Since this is not related to the project and is affected by the development environment, it's not the right place.
You should configure your **local git ignore** config to ignore such files.

2023-04-20 14:30 UTC, rimonsh commented on .gitignore
> +.idea/
done.

2023-04-20 14:30 UTC, rimonsh commented on poll_suggestion/models.py
> +class poll_suggestion(models.Model):
fixed.

2023-04-20 14:38 UTC, Sendy459 approved these changes

2023-04-20 14:42 UTC, kobihk requested changes

2023-04-20 14:42 UTC, kobihk commented on poll_suggestion/migrations/0001_initial.py
> +                ('poll_id', models.CharField(max_length=20)),
AFAICS in poll_suggestion/models.py you defined pool_id as models.ForeignKey like:
    poll_id = models.ForeignKey(Poll, on_delete=models.CASCADE)
so here it should be the same.
you probably need to migrate it again

2023-04-20 14:42 UTC, kobihk commented on poll_suggestion/models.py
> +class UserPollSuggestion(models.Model):
also, I can't see the migration file of this entity

2023-04-20 15:25 UTC, rimonsh commented on poll_suggestion/migrations/0001_initial.py
> +                ('poll_id', models.CharField(max_length=20)),
migrated.

2023-04-20 16:40 UTC, kobihk approved these changes

2023-04-20 16:44 UTC, Ofekmn approved these changes

2023-04-20 16:45 UTC, Sendy459 approved these changes

2023-04-22 22:48 UTC, merged