Update category model
redhat-beyond/FitMeet pull request #58
Opened 2023-04-19 21:20 UTC by Ofekmn

adds verification and the ability to update.

resolves #57

2023-04-20 06:23 UTC, talko611 reviewed
LGTM, please add update method tests

2023-04-20 07:30 UTC, rotem2022 approved these changes

2023-04-23 14:04 UTC, kobihk requested changes

2023-04-23 14:04 UTC, kobihk commented on category/tests.py
> +        assert category in Category.objects.all()
if you add unique=true as I suggested in the model file I think you can remove these lines
```suggestion

```

2023-04-23 14:04 UTC, kobihk commented on category/tests.py
> +        Category.objects.create(name=CATEGORY_NAME)
you can use the fixture category1 like:
```suggestion
    def test_category_with_same_name(self, category1):
```

2023-04-23 14:04 UTC, kobihk commented on category/tests.py
> +            Category.objects.create(name=CATEGORY_NAME)
please add validation tests like:
 * long name
 * empty name
 * special characters in the name

2023-04-24 08:19 UTC, kobihk commented on category/models.py
> +    name = models.CharField(max_length=20, unique=True, validators=[alpha])
Do we really want only alpha?
names like:
 * test category(with space)
 * test_category(with underscore)
will be invalid

2023-04-24 10:49 UTC, kobihk approved these changes

2023-04-24 20:32 UTC, kobihk submitted a review, later dismissed

2023-04-30 14:17 UTC, SaarOrus approved these changes
LGTM

2023-04-30 16:15 UTC, kobihk approved these changes

2023-04-30 17:59 UTC, rotem2022 approved these changes

2023-04-30 18:11 UTC, Sendy459 approved these changes

2023-04-30 18:59 UTC, talko611 approved these changes

2023-05-01 08:20 UTC, ygalblum approved these changes

2023-05-01 08:21 UTC, merged