Add tests for the location model
redhat-beyond/FitMeet pull request #60
Opened 2023-04-19 21:30 UTC by Ofekmn

add tests responsible for the location model

resolves #59

2023-04-20 06:23 UTC, talko611 reviewed
LGTM, please add update method tests

2023-04-20 14:16 UTC, ormergi commented
Hi Ofek, please take a look at my comment from another PR about tests that don't test the app business logic https://github.com/redhat-beyond/FitMeet/pull/26#discussion_r1171429021

2023-04-20 14:17 UTC, talko611 approved these changes

2023-04-24 21:14 UTC, kobihk requested changes

2023-04-24 21:14 UTC, kobihk commented on location/models.py
> +        self.description = description
maybe you can do one update method with all the options like:
```suggestion
    def update(self, name=None, city=None, street=None, street_number=None, indoor=None, description=None):
        if name:
            self.name = name
        if city:
            self.city = city
        if street:
            self.street = street
        if street_number:
            self.street_number = street_number
        if indoor is not None:
            self.indoor = indoor
        if description:
            self.description = description
```

2023-04-24 21:14 UTC, kobihk commented on location/models.py
> +        self.description = description
now in the test file, you can do all the tests in one test.
also, I think you can do something like "test_update_of_invalid_values"

2023-04-27 16:44 UTC, kobihk commented on location/models.py
> +            temp_location.name = name
I think it should be the same as using self
```suggestion
        if name is not None:
            self.name = name
            ...
```

2023-04-29 17:13 UTC, rotem2022 submitted a review, later dismissed
LGTM

2023-04-30 07:55 UTC, kobihk requested changes

2023-04-30 07:55 UTC, kobihk commented on location/tests.py
> +SPECIAL_CHARACTERS = "special%@chars"
you can also get all the special characters by doing:

```suggestion
import string

SPECIAL_CHARACTERS = string.punctuation
```
the output of string.punctuation is: '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

2023-04-30 07:55 UTC, kobihk commented on location/tests.py
> +    ],
you can enlarge the invalid tests to all the rest of the fields:
street_number, indoor, description

2023-04-30 07:55 UTC, kobihk commented on location/tests.py
> +    ],
same here ^^
you can enlarge the invalid update tests to all the rest of the fields:
street_number, indoor, description

2023-04-30 16:13 UTC, kobihk approved these changes

2023-04-30 18:00 UTC, rotem2022 approved these changes

2023-04-30 18:11 UTC, Sendy459 approved these changes

2023-05-01 08:23 UTC, ygalblum approved these changes

2023-05-01 08:23 UTC, merged