Add categoryLocation tests
redhat-beyond/FitMeet pull request #62
Opened 2023-04-19 21:39 UTC by Ofekmn

add tests responsible for the categoryLocation model

resolves #61

2023-04-19 21:41 UTC, Sendy459 submitted a review, later dismissed

2023-04-20 06:22 UTC, talko611 reviewed
I added comment
Also, you should check update methods

2023-04-20 06:22 UTC, talko611 commented on category_location/tests.py
> +            CategoryLocation.objects.get(pk=category_location1.pk)
There is a missing assert check
can also check this in this way:
`category_location1.delete()`
`assert category_location1 not in list(CategotryLocation.objects.all())`

2023-04-20 12:18 UTC, Ofekmn commented on category_location/tests.py
> +            CategoryLocation.objects.get(pk=category_location1.pk)
There is no need to add an assert check.
Pytest expects the CategoryLocation.DoesNotExist exception, and will fail the test if it isn't raised.

2023-04-20 14:15 UTC, ormergi commented
Hi Ofek, please take a look at my comment from another PR about tests that doesn't test the app business logic https://github.com/redhat-beyond/FitMeet/pull/26#discussion_r1171429021

2023-04-23 07:00 UTC, rotem2022 approved these changes
Looks Good

2023-04-23 14:55 UTC, talko611 approved these changes

2023-04-30 14:16 UTC, SaarOrus submitted a review, later dismissed

2023-04-30 18:02 UTC, rotem2022 submitted a review, later dismissed

2023-04-30 18:09 UTC, Sendy459 submitted a review, later dismissed

2023-04-30 18:59 UTC, talko611 approved these changes

2023-05-01 08:25 UTC, ygalblum requested changes

2023-05-01 08:25 UTC, ygalblum commented on category_location/tests.py
> +OTHER_DESCRIPTION = "description2"
You're not using any of these constants in the code. Did you mean to use them in `test_update_category_location`?

2023-05-01 12:37 UTC, Sendy459 submitted a review, later dismissed

2023-05-01 14:30 UTC, ygalblum commented on category_location/tests.py
> +        category_location1.update(category=category1, location=location1)
Why do you need this line?

2023-05-01 14:49 UTC, Ofekmn commented on category_location/tests.py
> +        category_location1.update(category=category1, location=location1)
When I did the PR that had Categoryn tests, Kobi suggested that I should check that the fields are correct before the update(https://github.com/redhat-beyond/FitMeet/pull/58)
I figured it should be like that here as well.

2023-05-01 15:56 UTC, rotem2022 approved these changes

2023-05-02 04:45 UTC, ygalblum commented on category_location/tests.py
> +        category_location1.update(category=category1, location=location1)
The `assert` lines I understand. But, then you update to the same values and don't check that the update happened (not sure you should). Am I reading this wrong? If I'm right, I don't understand why it is needed. If I'm wrong, can you please explain?

2023-05-02 06:30 UTC, SaarOrus approved these changes

2023-05-02 07:54 UTC, ygalblum approved these changes

2023-05-02 07:54 UTC, merged