Adding Poll tests
redhat-beyond/FitMeet pull request #64
Opened 2023-04-20 09:31 UTC by Sendy459

Adding tests to check the poll model

created tests.py file in poll app 

### Related Issue

Resolves #63 

#### Documentation

- [tests.py ] was updated in this PR

2023-04-20 10:48 UTC, Ofekmn submitted a review, later dismissed

2023-04-20 10:48 UTC, rotem2022 approved these changes

2023-04-20 10:51 UTC, SaarOrus submitted a review, later dismissed

2023-04-20 11:44 UTC, kobihk requested changes

2023-04-20 11:44 UTC, kobihk commented on poll/tests.py
> +def category_location(location_name=LOCATION, category_name=CATEGORY):
when you create a fixture to create an entity 
IMHO it will be better to create it like a param name like:
```suggestion
def category_location1(location_name=LOCATION, category_name=CATEGORY):
```

2023-04-20 11:44 UTC, kobihk commented on poll/tests.py
> +    location, category = create_sample_category_location(category_location, location_name)
if you use this method only here maybe it will be better to create lines # 19-27 here 
or maybe you can add the following 2 lines to the method create_sample_category_location

2023-04-20 11:44 UTC, kobihk commented on poll/tests.py
> +        assert poll not in Poll.objects.all()
Please read @ormergi comment about this kind of code:
https://github.com/redhat-beyond/FitMeet/pull/26#discussion_r1171429021

2023-04-20 11:44 UTC, kobihk commented on poll/tests.py
> +def create_poll(category_location):
same ^^ here 
```suggestion
def poll1(category_location):
```

2023-04-20 11:44 UTC, kobihk commented on poll/tests.py
> +        poll = create_poll
IMHO this line is redundant because you already get this variable 
```suggestion
```

2023-04-20 11:44 UTC, kobihk commented on poll/tests.py
> +        poll = create_poll
same ^^
```suggestion
```

2023-04-20 11:44 UTC, kobihk commented on poll/tests.py
> +        poll = create_poll
same ^^
```suggestion
```

2023-04-20 11:44 UTC, kobihk commented on poll/tests.py
> +        poll = create_poll
same ^^
```suggestion
```

2023-04-23 05:50 UTC, ormergi commented on poll/tests.py
> +        assert poll not in Poll.objects.all()
please take a look at my comment from another PR about tests that don't test the app business logic https://github.com/redhat-beyond/FitMeet/pull/26#discussion_r1171429021

2023-04-23 06:36 UTC, kobihk requested changes

2023-04-23 06:36 UTC, kobihk commented on poll/tests.py
> +@pytest.mark.django_db()
Now I think you can replace the django_db with:
```suggestion
@pytest.fixture
```

2023-04-23 06:36 UTC, kobihk commented on poll/tests.py
> +    )
also change it like:
```suggestion
def category_location1()
    loc = Location(
        name=LOCATION,
        city="test city",
        street="test street",
        street_number=1,
        indoor=False,
        description="test description",
    )
```
Now you can remove lines # 43-45

2023-04-23 06:36 UTC, kobihk commented on poll/tests.py
> +    cat = Category(name=cat_name)
```suggestion
    cat = Category(name=CATEGORY)
```

2023-04-24 08:13 UTC, kobihk requested changes

2023-04-24 08:13 UTC, kobihk commented on poll/tests.py
> +                                 is_private=IS_PRIVATE,)
I think you need to add event.save() otherwise it will not be persistent and the poll entity will be broken

2023-04-24 08:13 UTC, kobihk commented on poll/tests.py
> +                                 is_private=IS_PRIVATE,)
Maybe this is a good idea to add one more test that retrieves the poll from db and checks the event object

2023-04-24 19:45 UTC, kobihk approved these changes

2023-04-25 06:07 UTC, Ofekmn approved these changes

2023-04-25 15:18 UTC, talko611 reviewed
Basically, the whole idea of unit testing is to test if your model's functions do what you expect them to do, and not to compare between fields you are manually entered by yourself.
If you want to validate things on the object creation, create your own validators and check them.
I'm not sure which functionally you want to test in this PR, but since you didn't create additional functions to the defaults maybe check the default CRUD methods.

2023-04-25 15:18 UTC, talko611 commented on poll/tests.py
> +
Maybe I missing something here, but if you created manually the poll and the event, why do you need to check the validity between the participants' num and suggestion num?
You should only do this check if you have a validation function that checks it.

2023-04-25 16:08 UTC, rotem2022 submitted a review, later dismissed

2023-04-26 17:05 UTC, Sendy459 commented on poll/tests.py
> +
Yes, you're correct that the primary goal of unit testing is to ensure that the functions in your code behave as expected. In the context of Django models, this means testing that the methods and fields of your models work correctly.

When testing the fields of your models, you might want to check that the data is being saved and retrieved correctly, and that any custom validators or other business logic you've added to your models is working as expected. For example, if you've added a custom validator to ensure that a certain field can only accept specific values, you would want to write a unit test to make sure that the validator is working correctly. and this what I also understood from the Mentors point of view .

2023-04-26 17:05 UTC, Sendy459 commented on poll/tests.py
> +        assert poll1.end_time <= datetime.now() + timedelta(days=365)
checks that the pool end time is reasonable.

2023-04-26 17:05 UTC, Sendy459 commented on poll/tests.py
> +        assert poll1.end_time > poll1.event_id.start_time
You are right here it supposed to be in reverse I change it to poll1.end_time < poll1.event_id.start_time.Thanks.

2023-04-26 18:33 UTC, talko611 commented on poll/tests.py
> +
OK, but in your test, you statically create an object and check its data, the test will always be correct because static data doesn't have behavior. It seems a bit irrelevant to write tests like that.
If you what to check the data is saved correctly(meaning check the create and save data). you can create a test that creates an object and save it and then check if the object was saved to the database and its fields are the same as your input

2023-04-26 18:35 UTC, talko611 commented on poll/tests.py
> +        assert poll1.end_time <= datetime.now() + timedelta(days=365)
Same comment as the previous one. you are checking static data. if you want to check this case, create a validator function that checks this case and tests the function output.

2023-04-26 18:37 UTC, talko611 commented on poll/tests.py
> +        assert poll1.end_time > poll1.event_id.start_time
ok cool, but check my previous comments about what you should test in general.

2023-04-27 10:15 UTC, kobihk requested changes

2023-04-27 10:15 UTC, kobihk commented on poll/tests.py
> +
@Sendy459 In general, I think that is good to check every field. 
but the idea of @talko611 to retrieve it from the db as you did for example in line # 66:
        poll_from_db = Poll.objects.get(id=poll1.id)

could be better to make sure the data saved as expected in the db

btw now everything looks obvious but after a while, if someone else will refactor our code and change the type of one of the fields the basics tests could make him think twice about his change

2023-04-30 18:57 UTC, talko611 approved these changes

2023-05-02 06:28 UTC, SaarOrus approved these changes

2023-05-02 08:21 UTC, kobihk approved these changes

2023-05-02 08:21 UTC, merged