Add users tests
redhat-beyond/FitMeet pull request #66
Opened 2023-04-20 10:29 UTC by SaarOrus

This PR aims to add tests for the Profile model of the users app in order to ensure that it is working as expected. The tests cover the creation, deletion, updating, and string representation of a Profile object.
The changes made to the code include:

- Adding a __str__ function to the Profile model to provide a string representation of the Profile object.
- Changing the order of installed apps in the settings.py file.
- Adding tests to the tests.py file for the Profile model using pytest and fixtures.

Resolves #65

2023-04-20 11:05 UTC, Sendy459 submitted a review, later dismissed
LGTM

2023-04-20 11:08 UTC, rotem2022 submitted a review, later dismissed
Looks good to me.

2023-04-20 14:12 UTC, ormergi commented
Hi Saar, please take a look at my comment from another PR about tests that doesn't test the app business logic https://github.com/redhat-beyond/FitMeet/pull/26#discussion_r1171429021

2023-04-23 13:16 UTC, rotem2022 approved these changes

2023-04-23 14:22 UTC, kobihk requested changes

2023-04-23 14:22 UTC, kobihk commented on users/tests.py
> +def create_user():
The user in the fixture is used like a predefined user 
so IMHO it would be better to call it something like user1
```suggestion
def user1():
```

2023-04-23 14:22 UTC, kobihk commented on users/tests.py
> +        Profile.objects.create(user=create_user, date_of_birth=datetime.now(), phone_number='1234567890')
you use this line a few times maybe you can do it once as a fixture

2023-04-23 14:22 UTC, kobihk commented on users/tests.py
> +        new_phone_number = '0987654321'
maybe define it as constant:
PHONE_NUMBER_NEW = '0987654321'

2023-04-23 16:41 UTC, Sendy459 submitted a review, later dismissed

2023-04-27 07:49 UTC, rotem2022 approved these changes

2023-04-27 11:12 UTC, kobihk requested changes

2023-04-27 11:12 UTC, kobihk commented on users/tests.py
> +        assert updated_profile.phone_number == PHONE_NUMBER_NEW
maybe you can add a test of deleting a profile and make sure the related user is deleted too

2023-04-27 16:28 UTC, kobihk commented on users/tests.py
> +    return user
maybe it will be better to move the save to here instead of calling it a few times later 
```suggestion
    user.save()
    return user
```

2023-04-30 10:36 UTC, kobihk approved these changes
@SaarOrus please use "Resolve conversation" after you fixed a comment

2023-04-30 10:40 UTC, rotem2022 approved these changes

2023-04-30 12:15 UTC, Sendy459 approved these changes
LGTM

2023-04-30 16:18 UTC, merged