Generateteams
redhat-beyond/FitMeet pull request #74
Opened 2023-05-01 14:32 UTC by rotem2022

### What this PR does?

In this PR I added a method that gives an option to generate two teams based on an event.

### Notes for reviewer

I divided this PR into two commits

1. a stab commit witch contains files the changing depending on from #56 
2. a commit for changes relevant for this PR

### Related Issue

Resolves #73

#### Test coverage

- [x] This PR includes new unit and integration tests to go with the code
  changes
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

2023-05-02 04:46 UTC, ygalblum commented
@rotem2022 there's a conflict you need to fix

2023-05-02 15:16 UTC, rotem2022 commented
> @rotem2022 there's a conflict you need to fix

All done.

2023-05-04 07:48 UTC, talko611 requested changes

2023-05-04 07:48 UTC, talko611 commented on teams/models.py
> +                                 eventID=event_id).update(teamID=team2)
You are assuming that the number of users in the event is divisible by 2. but it is not the case, there are users that won't be entered into either one of the teams.

2023-05-04 09:13 UTC, rotem2022 commented on teams/models.py
> +        from event.models import UserEvent
The import cannot be placed at the top because it would cause a circular dependency between the team and event imports.

2023-05-04 09:17 UTC, rotem2022 commented on teams/models.py
> +                                 eventID=event_id).update(teamID=team2)
Actually, I am not making this assumptions. If the number of users in the event is not divisible by 2, then the second team will be larger. This can be seen in the test that has been conducted

2023-05-04 15:32 UTC, SaarOrus approved these changes

2023-05-05 12:38 UTC, talko611 commented on teams/models.py
> +        from event.models import UserEvent
Ok

2023-05-05 12:42 UTC, talko611 commented on teams/models.py
> +                                 eventID=event_id).update(teamID=team2)
Ok, sorry I missed that.
But then I don't understand the purpose of the team division if you sometimes get uneven teams.
I think you should divide the teams evenly and create another team with a special name and put there the participants that have no team

2023-05-07 09:09 UTC, rotem2022 commented on teams/models.py
> +                                 eventID=event_id).update(teamID=team2)
I appreciate your suggestion, but in this case, having a "special" team for participants who don't fit evenly into two teams might create an unnecessary distinction between participants. By having the second team be larger, we can avoid this and still have a fair and functional team division. Additionally, having two teams of unequal size can create a competitive advantage for the smaller team, which can add an interesting element to the event. Overall, I believe that leaving the teams uneven in certain cases can still achieve the desired outcome without creating unnecessary complexity.

2023-05-07 15:40 UTC, talko611 commented on teams/models.py
> +                                 eventID=event_id).update(teamID=team2)
Why is it an "unnecessary distinction"? this is equal to what happens in real life, you divide to equal teams and the leftovers are put in a special team. you can call this team "waiting" or "observers" to distinguish them from the regular teams.
I don't think somebody wishes to play a team sport with uneven teams and it misses the whole point of dividing into teams.

2023-05-07 16:46 UTC, talko611 submitted a review, later dismissed

2023-05-09 05:48 UTC, ygalblum commented on teams/tests.py
> +from event.models import UserEvent, Event
Please reorder the imports. Generally speaking there should be three sections: Python Standard, External and Internal. In this case, you don't import any standard libraries, the `pytest` and `django` imports are external and the rest is internal. In addition, make sure that each section is sorted alphabetically

2023-05-09 05:48 UTC, ygalblum commented on teams/tests.py
> +        team1 = []
Since you're just using the length of the arrays you can use counters instead of arrays.

2023-05-09 05:48 UTC, ygalblum commented on teams/tests.py
> +        assert len(generated_user_event_list) - team_size == len(team2)
AFAICS, this `assert` is redundant.
You append to `team2` everyone that is not on `team1`. As a result, `len(team1) + len(team2) == generated_user_event_list`. Now, since you've already asseted that `team_size == len(team1)`, the second assert basically checks that `len(generated_user_event_list) - len(team1) == len(team2)` which is true by definition.
Right?

2023-05-09 07:06 UTC, rotem2022 commented on teams/tests.py
> +        assert len(generated_user_event_list) - team_size == len(team2)
I believe both checks are necessary because of edge cases. For instance, let's consider the example where `len(generated_user_event_list)` = 5. So, 5//2 = 2. Therefore, `len(team1)` = 2 is correct, but it's possible that `len(team2) `could also be 2 instead of 3.

2023-05-09 07:10 UTC, rotem2022 commented on teams/tests.py
> +        team1 = []
yes I think you are right. thanks for the note.

2023-05-09 07:18 UTC, ygalblum commented on teams/tests.py
> +from event.models import UserEvent, Event
There's one django leftover

2023-05-09 09:27 UTC, rotem2022 commented on teams/tests.py
> +from event.models import UserEvent, Event
where is the leftover?

2023-05-09 11:20 UTC, ygalblum commented on teams/tests.py
> +from django.contrib.auth import get_user_model
Here it is :)

2023-05-09 13:04 UTC, rotem2022 commented on teams/tests.py
> +from django.contrib.auth import get_user_model
Thanks! changed (:

2023-05-10 09:49 UTC, SaarOrus approved these changes

2023-05-10 09:51 UTC, talko611 approved these changes

2023-05-10 10:27 UTC, ygalblum approved these changes

2023-05-10 10:27 UTC, merged