Adding a Poll Logic to the Polls app
redhat-beyond/FitMeet pull request #80
Opened 2023-05-02 20:21 UTC by Sendy459

main changes:
Adding create_poll method with validation to the Poll model Adding show_suggestions method to the Poll model

And testing for those methods

### What this PR does?

This PR adds  logic to the Poll app
And tests for the methods that were Added

### Notes for reviewer

Added methods to the model.py
and new tests for those methods in test.py

### Related Issue

Resolves #79 

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x ] This PR does not require updating any documentation

2023-05-02 20:24 UTC, Ofekmn submitted a review, later dismissed

2023-05-02 20:32 UTC, Ofekmn approved these changes

2023-05-04 12:56 UTC, rotem2022 commented
Great work overall! Just one small suggestion: there is a redundant space in the "Documentation" checkbox. It should be marked as [x] instead of [x ].

2023-05-06 08:53 UTC, rotem2022 approved these changes

2023-05-06 10:09 UTC, talko611 requested changes
Add a suggestion to one of the tests

2023-05-06 10:09 UTC, talko611 commented on poll/tests.py
> +            )
```suggestion
    def test_create_poll_with_invalid_end_time(self, event1):
        poll = Poll()
        with pytest.raises(ValidationError) as err:
            poll.create_poll(
                event=event1,
                max_suggestions=5,
                end_time=event1.start_time + timedelta(hours=1),
            )
        assert err.value.message == Poll.invalid_poll_error
```

2023-05-07 09:14 UTC, Ofekmn commented
Please rebase

2023-05-07 10:57 UTC, Ofekmn submitted a review, later dismissed

2023-05-07 10:57 UTC, rotem2022 approved these changes

2023-05-07 13:01 UTC, kobihk requested changes

2023-05-08 08:35 UTC, kobihk approved these changes

2023-05-09 09:33 UTC, merged