Add location migrations
redhat-beyond/FitMeet pull request #87
Opened 2023-05-07 14:18 UTC by Ofekmn

### What this PR does?

*Adds static location data for our app*

### Notes for reviewer

- Created another migration file and added a test for it.
- 

### Related Issue

Resolves #86 

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

2023-05-07 14:47 UTC, kobihk requested changes

2023-05-07 14:47 UTC, kobihk commented on location/migrations/0002_static_data.py
> +                            indoor=True, description='At the southern area')
instead of repeating the Location.objects.create a few times maybe you can do something like:
```suggestion
            location_test_data = [
            ('Bloomfield', 'Tel-Aviv-Yaffo', 'Hatkuma', 10,  False, 'A soccer field in tel-aviv'),
            ('Country Club TA A', 'Tel-Aviv-Yaffo', 'Rabbeinu Yerucham', 2, False, 'At the western area'),
            ...
        ]

        with transaction.atomic():
            for name, city, street, street_number, indoor, description in location_test_data:
                location = Location(name=name, city=city, street=street, street_number=street_number,
                            indoor=indoor, description=description)                
                location.save()
```

2023-05-08 08:11 UTC, kobihk approved these changes

2023-05-09 07:10 UTC, talko611 approved these changes

2023-05-09 17:03 UTC, rotem2022 approved these changes
Just wanted to bring a small issue to your attention. I noticed that there appears to be a redundant '*' in the test section of the PR description.

2023-05-10 09:38 UTC, merged