Adding base html file
redhat-beyond/FitMeet pull request #89
Opened 2023-05-08 11:28 UTC by rotem2022

### What this PR does?

In this PR I added a base HTML file.
update file:

-  fit_meet/urls.py
- static_home_page/templates/home_page/index.html
- static_home_page/views.py

### Related Issue

Resolves #88 

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [x] This PR does not require updating any documentation

2023-05-09 06:50 UTC, talko611 requested changes

2023-05-09 06:50 UTC, talko611 commented on static_home_page/templates/home_page/index.html
> +{% extends 'base.html'%} {%block content%}
Here I think we should extend the base.html and the block should be only what is inside the body tag

2023-05-09 06:50 UTC, talko611 commented on static_home_page/views.py
> +    return render(request, 'home_page/base.html')
If I understand correctly the base.html is the base for all pages but it should not be rendered.
The view should be removed

2023-05-09 06:50 UTC, talko611 commented on fit_meet/urls.py
> +    path('', views.base, name='base'),
The base.html should not be rendered by itself, so it doesn't need its own URL path

2023-05-09 06:50 UTC, talko611 commented on static_home_page/templates/base.html
> +    <div class="container">{% block content %} {% endblock %}</div>
isn't this content block should be inside a body tag?

2023-05-09 08:58 UTC, rotem2022 commented on static_home_page/templates/base.html
> +    <div class="container">{% block content %} {% endblock %}</div>
Yes I think you are right, I may accidently missed it.

2023-05-09 12:58 UTC, rotem2022 commented on static_home_page/templates/home_page/index.html
> +{% extends 'base.html'%} {%block content%}
I made some changes, pleas review

2023-05-09 13:54 UTC, Sendy459 approved these changes

2023-05-09 18:01 UTC, talko611 requested changes

2023-05-09 18:01 UTC, talko611 commented on static_home_page/templates/base.html
> +		<title>Startup Landing Page</title>
```suggestion
		<title>FitMeet</title>
```

2023-05-09 18:03 UTC, talko611 commented on static_home_page/templates/base.html
> +		<h1 style="color: darkcyan;">Welcome to FitMeet</h1>
I meant the h1 tag

2023-05-09 18:30 UTC, rotem2022 commented on static_home_page/templates/base.html
> +		<h1 style="color: darkcyan;">Welcome to FitMeet</h1>
maybe we can remove the "welcome"

2023-05-10 09:45 UTC, rotem2022 commented on static_home_page/templates/base.html
> +  <body>
All done. Thanks for the note!

2023-05-10 09:49 UTC, SaarOrus submitted a review, later dismissed

2023-05-10 09:52 UTC, Sendy459 submitted a review, later dismissed

2023-05-10 10:25 UTC, kobihk requested changes

2023-05-10 10:25 UTC, kobihk commented on static_home_page/templates/base.html
> +<body>
I think this tag is redundant because you have the same one in line # 23
```suggestion
```

2023-05-10 10:25 UTC, kobihk commented on static_home_page/templates/base.html
> +	</header>
please fix the indentation

2023-05-10 10:25 UTC, kobihk commented on static_home_page/templates/base.html
> +    <div class="container">{% block content %} {% endblock %}</div>
maybe it will be more readable like:
```suggestion
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
```

2023-05-10 10:25 UTC, kobihk commented on static_home_page/templates/home_page/index.html
> +{%endblock%}
please add a spaces to make it more readable like:
```suggestion
{% endblock %}
```

2023-05-10 10:25 UTC, kobihk commented on static_home_page/templates/home_page/index.html
> +<html lang="en">
you already have it in base.html so I think you can delete this line
```suggestion
```

2023-05-10 10:32 UTC, rotem2022 commented on static_home_page/templates/base.html
> +<body>
Yes thank you I missed it.

2023-05-10 10:35 UTC, rotem2022 commented on static_home_page/templates/home_page/index.html
> +<html lang="en">
Yes I noticed but wasnt sure.

2023-05-10 10:44 UTC, Sendy459 approved these changes

2023-05-10 10:57 UTC, kobihk approved these changes

2023-05-10 11:07 UTC, SaarOrus approved these changes

2023-05-10 11:27 UTC, rotem2022 commented on static_home_page/templates/base.html
> +		<link rel="stylesheet" href="{% static 'web_page_css.css' %}">
I'm having trouble understanding your approach. Could you please clarify how and what you would like the changes to be made?

2023-05-10 12:14 UTC, talko611 commented on static_home_page/templates/base.html
> +		<link rel="stylesheet" href="{% static "web_page_css.css" %}">
```suggestion
		{% block extrahead %}{% endblock %}
```
This line will allow to each block inject its own style sheet. 
On each sub-template, we need to specify the following blocks:
{% extends "base.html" %}

{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/child.css' %}">
{% endblock %}

{% block content %}
    the content of the template
{% endblock %}

2023-05-10 13:05 UTC, rotem2022 commented on static_home_page/templates/base.html
> +		<link rel="stylesheet" href="{% static "web_page_css.css" %}">
In your suggestion, it seems like you want to replace line 9 with "{% block extrahead %}
{% endblock %}". However, doing so would remove the CSS from the base.html file. Did you perhaps mean to add this line somewhere else?

2023-05-10 13:35 UTC, Sendy459 commented on static_home_page/templates/base.html
> +		<link rel="stylesheet" href="{% static "web_page_css.css" %}">
The whole Idea is that we all agreed with to use the same style sheet as in the index.html for the whole project In our meeting on Sunday that you missed btw so maybe we forgot to mention . if this style does not match part of a page you are working on sure you can use this {% block extrahead %}{% endblock %} to inject another style.

2023-05-14 08:24 UTC, rotem2022 commented on static_home_page/templates/base.html
> +		<link rel="stylesheet" href="{% static "web_page_css.css" %}">
I Thought about your suggestion, but I think it is better to leave it as it is because IMHO
Having a separate CSS file for each web page can make it easier to manage and maintain the styles specific to that page. It allows for clear separation of concerns, making it easier to understand and update the styles for a particular page without affecting others.

However, if our website is relatively small and consists of just a few pages, combining the CSS into a single file might be more efficient.
Combining multiple CSS files into a single file reduces the number of separate requests needed for CSS resources. Instead of making individual requests for each CSS file, the browser can fetch and load a single CSS file, resulting in fewer round trips to the server. This consolidation reduces the overhead associated with establishing and managing multiple network connections, resulting in faster page load times.

2023-05-14 08:28 UTC, talko611 commented on static_home_page/templates/base.html
> +		<link rel="stylesheet" href="{% static "web_page_css.css" %}">
That is another approach, but everybody should be cautious when applying new styles. it can cause many bugs by overriding styles.

2023-05-14 08:29 UTC, talko611 approved these changes

2023-05-14 08:36 UTC, Sendy459 approved these changes

2023-05-15 06:48 UTC, merged