Add profile migrations
redhat-beyond/FitMeet pull request #97
Opened 2023-05-15 19:53 UTC by Ofekmn

Added migrations to have static profiles for our app

### What this PR does?

Adds some users to our app

### Notes for reviewer

adds migrations and a test for it

### Related Issue

Resolves #[relevant issue(s), e.g. 37]

#### Test coverage

- [X] This PR includes new unit and integration tests to go with the code
  changes
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [X] This PR does not require updating any documentation

2023-05-16 07:49 UTC, rotem2022 approved these changes
looks good!

2023-05-16 07:55 UTC, talko611 approved these changes

2023-05-16 08:40 UTC, kobihk requested changes

2023-05-16 08:40 UTC, kobihk commented on users/migrations/0002_static_data.py
> +            profile.save()
maybe you can do it simply with one loop like:
```suggestion
    profile_data = [
        ('Ofek', 'qaz[;.123', datetime(2020, 5, 17), '050-123456789'),
        ('Danny', 'qaz[;.123', datetime(2020, 5, 17), '050-223456789'),
        ('Rimon', 'qaz[;.123', datetime(2020, 5, 17), '050-323456789'),
        ('Rotem', 'qaz[;.123', datetime(2020, 5, 17), '050-423456789'),
        ('Saar', 'qaz[;.123', datetime(2020, 5, 17), '050-523456789'),
        ('Tal', 'qaz[;.123', datetime(2020, 5, 17), '050-623456789'),
    ]

    with transaction.atomic():
        for username, password, dob, phone_number in profile_data:
            user = User(username=username, password=password)
            user.save()
            profile = Profile(user=user, date_of_birth=dob, phone_number=phone_number)
            profile.save()

```

2023-05-17 04:36 UTC, rotem2022 approved these changes

2023-05-17 06:54 UTC, SaarOrus approved these changes

2023-05-17 06:54 UTC, SaarOrus approved these changes

2023-05-17 07:48 UTC, kobihk approved these changes

2023-05-17 07:48 UTC, merged